services:
  frontend:
    image: akshathaa16/swiftbites-frontend:latest
    platform: linux/amd64
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_HOST=0.0.0.0
    command: npm run dev -- --host 0.0.0.0
    networks:
      - swiftbites-network

  backend:
    image: akshathaa16/swiftbites-backend:latest
    platform: linux/amd64
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGODB_URI=mongodb+srv://aj7301925:kX4OaZwnDKVrOIB0@cluster0.9zivhnj.mongodb.net/food-del
    networks:
      - swiftbites-network

  admin:
    image: akshathaa16/swiftbites-admin:latest
    platform: linux/amd64
    ports:
      - "5174:5173"
    depends_on:
      - backend
    environment:
      - VITE_HOST=0.0.0.0
    command: npm run dev -- --host 0.0.0.0
    networks:
      - swiftbites-network

networks:
  swiftbites-network:
    driver: bridge

