version: '3'

services:
  frontend:
    image: akshathaa16/swiftbites-frontend:latest
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    image: akshathaa16/swiftbites-backend:latest
    ports:
      - "4000:4000"
    environment:
      - PORT=4000

  admin:
    image: akshathaa16/swiftbites-admin:latest
    ports:
      - "5174:5174"
    depends_on:
      - backend
